### PR TITLE
QuickBlox-Hacktoberfest-Challenge: Create anonymous-poll.md

### PR DESCRIPTION
**Pull request by abhirajadhikary06**
I am excited to submit my project, Anonymous Poll, for the QuickBlox Hacktoberfest Challenge. This is my first time developing with QuickBlox and contributing to an open-source project, and I am thrilled to have started this journey with your platform.

Anonymous Poll is a real-time anonymous polling system that allows users to cast votes and view updated poll results in real-time through a simple chat interface. The project is built using QuickBlox's JavaScript SDK for real-time communication and Flask for backend logic.

@SayantaniDeb if you are maintainer or reviewer of the repository please checkout my PR.

### CODE REVIEW

**Comment by SayantaniDeb** [comment]
Thank you for submitting your project @abhirajadhikary06 ! It sounds amazing, and we're excited to see your contribution. Please allow us some time to review your pull request, and we will get back to you soon.

**Comment by abhirajadhikary06** [comment]
Yeah sure, take your time.

**Comment by SayantaniDeb** [comment]
Hey @abhirajadhikary06 , can you also attach a working video of the project. We will merge as soon as the requirements are fulfilled.

Video limit: within 1 minute. [a screen recorded video will also work]

**Comment by abhirajadhikary06** [comment]
@SayantaniDeb Please check I have uploaded the video in the markdown file. 
The same can be viewed from here if you wish to : https://drive.google.com/file/d/1sH0F1rUw_Ks1rmfXs59lGA5udaGK_wCk/view?usp=sharing

**Comment by abhirajadhikary06** [comment]
Thank you 😊

**Comment by SayantaniDeb** [comment]
Hi @abhirajadhikary06 , feel free to claim your prize for the merged PR, and wait till the challenge ends for the final result prize. 🏆 - [Link](https://docs.google.com/forms/d/e/1FAIpQLSc5g4um52B-8MQOVXgse_V3JMgyX6dIC7hVbrl_Uck4IcLEiQ/viewform)

**Comment by abhirajadhikary06** [comment]
Thanks for updating. 😊

**Comment by abhirajadhikary06** [comment]
Subject: Follow-up on Prize Claim Submission for Quickblox Challenge

Dear Sayantani,

I hope this email finds you well.

A few days ago, I received an email from your team regarding the Prize Claim form I had submitted for the QuickBlox Hacktoberfest Challenge. It mentioned that my Pull Request (PR) could not be located. I would like to clarify that my PR was made before the event's closing deadline.

In response to your email, I promptly replied with the PR link and also attached a PDF detailing the same information, which I had previously submitted through the Google form on the QuickBlox Challenge GitHub page.

For your convenience, I am sharing the link to my PR once again:
https://github.com/QuickBlox/quickblox-hacktoberfest-challenge/pull/4

I kindly request you to review my submission at your earliest convenience. Could you please confirm if I am eligible to receive the swags associated with the event?

Thank you for your time and assistance. I look forward to your response.

Best regards,
Abhiraj

**Pull request merged**
